# Generated by Django 4.2.9 on 2024-01-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateTimeField(auto_now=True)),
                ('pno', models.CharField(max_length=250)),
                ('mail', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('cources', models.CharField(max_length=250)),
                ('purpose', models.CharField(max_length=250)),
                ('materials', models.CharField(max_length=250)),
            ],
        ),
    ]
