# Generated by Django 4.2.9 on 2024-01-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='genders',
            field=models.CharField(default='male', max_length=250),
            preserve_default=False,
        ),
    ]
