# Generated by Django 4.2.9 on 2024-01-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_store_genders'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='age',
            field=models.IntegerField(default='22'),
            preserve_default=False,
        ),
    ]
