# Generated by Django 4.2.9 on 2024-01-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_store_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='age',
            field=models.CharField(max_length=250),
        ),
    ]
